"""empty message

Revision ID: 8424811bcb74
Revises: 3e89f92a7baf
Create Date: 2017-08-22 13:43:53.500111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8424811bcb74'
down_revision = '3e89f92a7baf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shoppinglist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shoppingitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=60), nullable=True),
    sa.Column('shoppinglist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shoppinglist_id'], ['shoppinglist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shoppingitem')
    op.drop_table('shoppinglist')
    # ### end Alembic commands ###
